port = 8888
release = true              # when work in release mode: set this to true, otherwise to false and enviornment variable GIN_MODE not to release


[aria2]
aria2_download_dir = "/ipfs/"   # Directory where offline deal files will be downloaded for importing
aria2_host = "127.0.0.1"  # Aria2 server address
aria2_port = 6800         # Aria2 server port
aria2_secret = "my_aria2_secret"  # Must be the same value as rpc-secure in aria2.conf
aria2_max_task = 10  # downloading  max  limit


[main]
LogName = "./logs"



[mysql]
DbType = "mysql"
host = "10.0.3.1"  #
port = 3306
dbname = "aria2"
users = "root"
passwd = "yungo2020!@"
table = "filswan"
enable = false

[logs]
maxsize = 1024   #   file max size  1024M
backups = 10  # file backup 10 day
day = 7  #
level = "DEBUG" # level  Debug

[watch]
enable = false

[disk]
drive = "2"

